// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJeWAUJZf9ojgO_pUCFCwyA83cjEO3FI',
    appId: '1:438585788509:web:654abe46a7b035f044e5b4',
    messagingSenderId: '438585788509',
    projectId: 'parcial-4-etps3',
    authDomain: 'parcial-4-etps3.firebaseapp.com',
    storageBucket: 'parcial-4-etps3.appspot.com',
    measurementId: 'G-FDLBKEKEQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDQNmZS_wvO5r-niEj27vgBHzNuUj-FZI',
    appId: '1:438585788509:android:bfd2322d042119c944e5b4',
    messagingSenderId: '438585788509',
    projectId: 'parcial-4-etps3',
    storageBucket: 'parcial-4-etps3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULxqH8g4l_842QpRr4CKZBptBkmt1m7A',
    appId: '1:438585788509:ios:bb4ce25e6216ab5f44e5b4',
    messagingSenderId: '438585788509',
    projectId: 'parcial-4-etps3',
    storageBucket: 'parcial-4-etps3.appspot.com',
    iosClientId: '438585788509-b1t5ehe89mukcfr6f3qa5i1k9vvaa0da.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULxqH8g4l_842QpRr4CKZBptBkmt1m7A',
    appId: '1:438585788509:ios:41e0e5f42f275a6b44e5b4',
    messagingSenderId: '438585788509',
    projectId: 'parcial-4-etps3',
    storageBucket: 'parcial-4-etps3.appspot.com',
    iosClientId: '438585788509-2b394mhqo2jdtd308eaht9t5p7p2ucrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcial4.RunnerTests',
  );
}
